apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfdemorepository1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBdpG+huo+C4Z8YuzS9MAGZ85oYWvULkNSvB7zDf9p5u92QcMucG1Cos+knxqDDGMGHWdcVnXzTwNFEX7m3X2zs6qnAMau8wrTJbu/X31dHlH+JjYGcr08itQC7adaMUyf1DaOalSmKcTYmC7/RhzkLfb0CNSE3XgsYrR2eLarV6K/Uig0485JAayRqIChKTs8bbs5j798dMmYKM4e/x5p4x5Qxj614KmnDWPsNmF1C9bikGHIx1Bjev5Ou/9oG2T+PtQtDxX53zQZfkzIPOoHhMlYatESkAEQjLAPj34ojofI5somOaaNKIzf8aeun2pd6t2OGJu6Hrz7xJsmy3X392WfNUnwFJhQOk7a5/y1cYruMroIy0MazYn8P2GWiqTIVeT1TobekM3iRkzFoyr3HkecsnFR3dDW9/tIwk2rwCSwX7+U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: tfdemorepository1
      namespace: default