apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: workload1 
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://my-pod-chart-0.1.0.tgz
    options: {}
    type: Helm4
  namespace: ns4
  placement:
    selector: rafay.dev/clusterName=kratos-rishabh-1
