apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-busybox
  labels:
    app.kubernetes.io/name: busybox
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: busybox
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busybox
        app.kubernetes.io/instance: test
    spec:
      securityContext:
        {}
      containers:
        - name: busybox
          securityContext:
            {}
          image: "busybox:latest"
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          env:
          - name: "DEBUG_DATA"
            value: "Rafay"
          resources:
            {}