#!/usr/bin/env bash
# Provide default RAFAY CI env vars (source before invoking tests)
: "${RCTL_PROJECT:=defaultproject}"
: "${RCTL_PROFILE:=dev}"
: "${RCTL_REST_ENDPOINT:=console-tb.dev.rafay-edge.net}"
: "${RCTL_OPS_ENDPOINT:=ops-console-tb.dev.rafay-edge.net}"
: "${RCTL_API_KEY:=**********}"
: "${RCTL_API_SECRET:=**********}"
: "${RCTL_SKIP_SERVER_CERT_VALIDATION:=false}"
: "${RCTL_ORGANIZATION:=defaultorg}"
: "${BASE_BLUEPRINT_VERSION:=4.0.0}"
export RCTL_PROJECT RCTL_PROFILE RCTL_REST_ENDPOINT RCTL_OPS_ENDPOINT \
  RCTL_API_KEY RCTL_API_SECRET RCTL_SKIP_SERVER_CERT_VALIDATION \
  RCTL_ORGANIZATION BASE_BLUEPRINT_VERSION

echo "environment variables:"
echo "  RCTL_PROJECT=$RCTL_PROJECT"
echo "  RCTL_PROFILE=$RCTL_PROFILE"
echo "  RCTL_REST_ENDPOINT=$RCTL_REST_ENDPOINT"
echo "  RCTL_OPS_ENDPOINT=$RCTL_OPS_ENDPOINT"
echo "  RCTL_API_KEY=$RCTL_API_KEY"
echo "  RCTL_API_SECRET=$RCTL_API_SECRET"
echo "  RCTL_SKIP_SERVER_CERT_VALIDATION=$RCTL_SKIP_SERVER_CERT_VALIDATION"
echo "  RCTL_ORGANIZATION=$RCTL_ORGANIZATION"
echo "  BASE_BLUEPRINT_VERSION=$BASE_BLUEPRINT_VERSION"
