name: Release Branch Tag Workflow

on:
  workflow_dispatch:  # manually trigger the workflow
    inputs:
      release_branch:
        description: 'New branch release branch name Ex: vx.xx.xx'
        required: true
      release_branch_tag:
        description: 'Release banch tag. Ex: r1.2.3'
        required: true

jobs:
  branch-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v2  # This action checks out the branch associated with the PR

    - name: Set Git config
      run: |
        git config user.email "jenkins@rafay.co"
        git config user.name "jenkinsrafay"
    - name: Create tag on the release branch
      run: |
        git branch
        git fetch --all
        git checkout ${{ github.event.inputs.release_branch }}
        git log -1
        git pull origin ${{ github.event.inputs.release_branch }}
        git rebase origin/${{ github.event.inputs.release_branch }}
        git tag -a ${{ github.event.inputs.release_branch_tag }} -m "${{ github.event.inputs.release_branch_tag }} Release"
        git push origin ${{ github.event.inputs.release_branch_tag }}
