name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v1.12.8
        with:
          GITHUB_TOKEN: ${{ secrets.JENKINS_PAT }}
          GITHUB_REPO_FOR_ISSUE: "terraform-provider-rafay"
          GITHUB_OWNER_FOR_ISSUE: "RafaySystems"
          GITHUB_OWNERS_REPOS: "RafaySystems/terraform-provider-rafay"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "UTC"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
